favfastfood=input("What is your favorite fast food?")
print("Your favorite fast food place is " + favfastfood + "?")
answer=input("yes or no?")
print("Your favorite fast food isn't Black Bear Diner?")
answer2=input("yes it is or no it isn't?")
print("well, the correct answer is Chic-Fil-A. Indisputable.")
correctanswer=input("Did you choose Chic-Fil-A?")
print("Good. " + favfastfood + " is not as good as Chic-Fil-A.")